/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables.records;


import com.experts.core.biller.statemachine.api.jooq.tables.AccountDetails;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountDetailsRecord extends UpdatableRecordImpl<AccountDetailsRecord> implements Record12<Long, Timestamp, String, Timestamp, String, String, String, Integer, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = -117759949;

    /**
     * Setter for <code>public.account_details.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account_details.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.account_details.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account_details.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.account_details.lastmodifiedby</code>.
     */
    public void setLastmodifiedby(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account_details.lastmodifiedby</code>.
     */
    public String getLastmodifiedby() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.account_details.modifieddate</code>.
     */
    public void setModifieddate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.account_details.modifieddate</code>.
     */
    public Timestamp getModifieddate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.account_details.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.account_details.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.account_details.account_name</code>.
     */
    public void setAccountName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.account_details.account_name</code>.
     */
    public String getAccountName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.account_details.account_number</code>.
     */
    public void setAccountNumber(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.account_details.account_number</code>.
     */
    public String getAccountNumber() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.account_details.balance</code>.
     */
    public void setBalance(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.account_details.balance</code>.
     */
    public Integer getBalance() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.account_details.isbn</code>.
     */
    public void setIsbn(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.account_details.isbn</code>.
     */
    public String getIsbn() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.account_details.max_queue_tx</code>.
     */
    public void setMaxQueueTx(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.account_details.max_queue_tx</code>.
     */
    public Integer getMaxQueueTx() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.account_details.maxtx</code>.
     */
    public void setMaxtx(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.account_details.maxtx</code>.
     */
    public Integer getMaxtx() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.account_details.version</code>.
     */
    public void setVersion(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.account_details.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Timestamp, String, Timestamp, String, String, String, Integer, String, Integer, Integer, Integer> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Timestamp, String, Timestamp, String, String, String, Integer, String, Integer, Integer, Integer> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AccountDetails.ACCOUNT_DETAILS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return AccountDetails.ACCOUNT_DETAILS.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AccountDetails.ACCOUNT_DETAILS.LASTMODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return AccountDetails.ACCOUNT_DETAILS.MODIFIEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AccountDetails.ACCOUNT_DETAILS.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AccountDetails.ACCOUNT_DETAILS.ACCOUNT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AccountDetails.ACCOUNT_DETAILS.ACCOUNT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return AccountDetails.ACCOUNT_DETAILS.BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return AccountDetails.ACCOUNT_DETAILS.ISBN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return AccountDetails.ACCOUNT_DETAILS.MAX_QUEUE_TX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return AccountDetails.ACCOUNT_DETAILS.MAXTX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return AccountDetails.ACCOUNT_DETAILS.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAccountName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAccountNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getIsbn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getMaxQueueTx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getMaxtx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAccountName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAccountNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getIsbn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getMaxQueueTx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getMaxtx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value2(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value3(String value) {
        setLastmodifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value4(Timestamp value) {
        setModifieddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value5(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value6(String value) {
        setAccountName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value7(String value) {
        setAccountNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value8(Integer value) {
        setBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value9(String value) {
        setIsbn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value10(Integer value) {
        setMaxQueueTx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value11(Integer value) {
        setMaxtx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord value12(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetailsRecord values(Long value1, Timestamp value2, String value3, Timestamp value4, String value5, String value6, String value7, Integer value8, String value9, Integer value10, Integer value11, Integer value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountDetailsRecord
     */
    public AccountDetailsRecord() {
        super(AccountDetails.ACCOUNT_DETAILS);
    }

    /**
     * Create a detached, initialised AccountDetailsRecord
     */
    public AccountDetailsRecord(Long id, Timestamp createddate, String lastmodifiedby, Timestamp modifieddate, String username, String accountName, String accountNumber, Integer balance, String isbn, Integer maxQueueTx, Integer maxtx, Integer version) {
        super(AccountDetails.ACCOUNT_DETAILS);

        set(0, id);
        set(1, createddate);
        set(2, lastmodifiedby);
        set(3, modifieddate);
        set(4, username);
        set(5, accountName);
        set(6, accountNumber);
        set(7, balance);
        set(8, isbn);
        set(9, maxQueueTx);
        set(10, maxtx);
        set(11, version);
    }
}
