/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables.records;


import com.experts.core.biller.statemachine.api.jooq.tables.BankServiceCatogery;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankServiceCatogeryRecord extends UpdatableRecordImpl<BankServiceCatogeryRecord> implements Record9<Long, Timestamp, String, Timestamp, String, Boolean, String, byte[], Integer> {

    private static final long serialVersionUID = -218166419;

    /**
     * Setter for <code>public.bank_service_catogery.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bank_service_catogery.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.bank_service_catogery.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bank_service_catogery.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.bank_service_catogery.lastmodifiedby</code>.
     */
    public void setLastmodifiedby(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bank_service_catogery.lastmodifiedby</code>.
     */
    public String getLastmodifiedby() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.bank_service_catogery.modifieddate</code>.
     */
    public void setModifieddate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bank_service_catogery.modifieddate</code>.
     */
    public Timestamp getModifieddate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.bank_service_catogery.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bank_service_catogery.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.bank_service_catogery.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.bank_service_catogery.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.bank_service_catogery.service_name</code>.
     */
    public void setServiceName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.bank_service_catogery.service_name</code>.
     */
    public String getServiceName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.bank_service_catogery.type</code>.
     */
    public void setType(byte... value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.bank_service_catogery.type</code>.
     */
    public byte[] getType() {
        return (byte[]) get(7);
    }

    /**
     * Setter for <code>public.bank_service_catogery.version</code>.
     */
    public void setVersion(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.bank_service_catogery.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Timestamp, String, Timestamp, String, Boolean, String, byte[], Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Timestamp, String, Timestamp, String, Boolean, String, byte[], Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BankServiceCatogery.BANK_SERVICE_CATOGERY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return BankServiceCatogery.BANK_SERVICE_CATOGERY.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BankServiceCatogery.BANK_SERVICE_CATOGERY.LASTMODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return BankServiceCatogery.BANK_SERVICE_CATOGERY.MODIFIEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BankServiceCatogery.BANK_SERVICE_CATOGERY.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return BankServiceCatogery.BANK_SERVICE_CATOGERY.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BankServiceCatogery.BANK_SERVICE_CATOGERY.SERVICE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field8() {
        return BankServiceCatogery.BANK_SERVICE_CATOGERY.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return BankServiceCatogery.BANK_SERVICE_CATOGERY.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getServiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component8() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getServiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value8() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankServiceCatogeryRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankServiceCatogeryRecord value2(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankServiceCatogeryRecord value3(String value) {
        setLastmodifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankServiceCatogeryRecord value4(Timestamp value) {
        setModifieddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankServiceCatogeryRecord value5(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankServiceCatogeryRecord value6(Boolean value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankServiceCatogeryRecord value7(String value) {
        setServiceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankServiceCatogeryRecord value8(byte... value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankServiceCatogeryRecord value9(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankServiceCatogeryRecord values(Long value1, Timestamp value2, String value3, Timestamp value4, String value5, Boolean value6, String value7, byte[] value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BankServiceCatogeryRecord
     */
    public BankServiceCatogeryRecord() {
        super(BankServiceCatogery.BANK_SERVICE_CATOGERY);
    }

    /**
     * Create a detached, initialised BankServiceCatogeryRecord
     */
    public BankServiceCatogeryRecord(Long id, Timestamp createddate, String lastmodifiedby, Timestamp modifieddate, String username, Boolean deleted, String serviceName, byte[] type, Integer version) {
        super(BankServiceCatogery.BANK_SERVICE_CATOGERY);

        set(0, id);
        set(1, createddate);
        set(2, lastmodifiedby);
        set(3, modifieddate);
        set(4, username);
        set(5, deleted);
        set(6, serviceName);
        set(7, type);
        set(8, version);
    }
}
