/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables.records;


import com.experts.core.biller.statemachine.api.jooq.tables.CompletedState;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompletedStateRecord extends UpdatableRecordImpl<CompletedStateRecord> implements Record16<Long, Timestamp, String, Timestamp, String, String, String, String, String, String, String, Boolean, String, String, String, Long> {

    private static final long serialVersionUID = -1740843761;

    /**
     * Setter for <code>public.completed_state.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.completed_state.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.completed_state.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.completed_state.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.completed_state.lastmodifiedby</code>.
     */
    public void setLastmodifiedby(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.completed_state.lastmodifiedby</code>.
     */
    public String getLastmodifiedby() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.completed_state.modifieddate</code>.
     */
    public void setModifieddate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.completed_state.modifieddate</code>.
     */
    public Timestamp getModifieddate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.completed_state.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.completed_state.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.completed_state.bill_code</code>.
     */
    public void setBillCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.completed_state.bill_code</code>.
     */
    public String getBillCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.completed_state.bill_no</code>.
     */
    public void setBillNo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.completed_state.bill_no</code>.
     */
    public String getBillNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.completed_state.biller_code</code>.
     */
    public void setBillerCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.completed_state.biller_code</code>.
     */
    public String getBillerCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.completed_state.biller_name</code>.
     */
    public void setBillerName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.completed_state.biller_name</code>.
     */
    public String getBillerName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.completed_state.code</code>.
     */
    public void setCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.completed_state.code</code>.
     */
    public String getCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.completed_state.execption</code>.
     */
    public void setExecption(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.completed_state.execption</code>.
     */
    public String getExecption() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.completed_state.sucess</code>.
     */
    public void setSucess(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.completed_state.sucess</code>.
     */
    public Boolean getSucess() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.completed_state.message</code>.
     */
    public void setMessage(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.completed_state.message</code>.
     */
    public String getMessage() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.completed_state.name</code>.
     */
    public void setName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.completed_state.name</code>.
     */
    public String getName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.completed_state.transaction_id</code>.
     */
    public void setTransactionId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.completed_state.transaction_id</code>.
     */
    public String getTransactionId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.completed_state.processstate_completedstate</code>.
     */
    public void setProcessstateCompletedstate(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.completed_state.processstate_completedstate</code>.
     */
    public Long getProcessstateCompletedstate() {
        return (Long) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, Timestamp, String, Timestamp, String, String, String, String, String, String, String, Boolean, String, String, String, Long> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, Timestamp, String, Timestamp, String, String, String, String, String, String, String, Boolean, String, String, String, Long> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CompletedState.COMPLETED_STATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return CompletedState.COMPLETED_STATE.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CompletedState.COMPLETED_STATE.LASTMODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return CompletedState.COMPLETED_STATE.MODIFIEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CompletedState.COMPLETED_STATE.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CompletedState.COMPLETED_STATE.BILL_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CompletedState.COMPLETED_STATE.BILL_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CompletedState.COMPLETED_STATE.BILLER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CompletedState.COMPLETED_STATE.BILLER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CompletedState.COMPLETED_STATE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return CompletedState.COMPLETED_STATE.EXECPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return CompletedState.COMPLETED_STATE.SUCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return CompletedState.COMPLETED_STATE.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return CompletedState.COMPLETED_STATE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return CompletedState.COMPLETED_STATE.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return CompletedState.COMPLETED_STATE.PROCESSSTATE_COMPLETEDSTATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getBillCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getBillNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getBillerCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getBillerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getExecption();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getSucess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component16() {
        return getProcessstateCompletedstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getBillCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getBillNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getBillerCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getBillerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getExecption();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getSucess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getProcessstateCompletedstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value2(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value3(String value) {
        setLastmodifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value4(Timestamp value) {
        setModifieddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value5(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value6(String value) {
        setBillCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value7(String value) {
        setBillNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value8(String value) {
        setBillerCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value9(String value) {
        setBillerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value10(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value11(String value) {
        setExecption(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value12(Boolean value) {
        setSucess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value13(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value14(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value15(String value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord value16(Long value) {
        setProcessstateCompletedstate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompletedStateRecord values(Long value1, Timestamp value2, String value3, Timestamp value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, Boolean value12, String value13, String value14, String value15, Long value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompletedStateRecord
     */
    public CompletedStateRecord() {
        super(CompletedState.COMPLETED_STATE);
    }

    /**
     * Create a detached, initialised CompletedStateRecord
     */
    public CompletedStateRecord(Long id, Timestamp createddate, String lastmodifiedby, Timestamp modifieddate, String username, String billCode, String billNo, String billerCode, String billerName, String code, String execption, Boolean sucess, String message, String name, String transactionId, Long processstateCompletedstate) {
        super(CompletedState.COMPLETED_STATE);

        set(0, id);
        set(1, createddate);
        set(2, lastmodifiedby);
        set(3, modifieddate);
        set(4, username);
        set(5, billCode);
        set(6, billNo);
        set(7, billerCode);
        set(8, billerName);
        set(9, code);
        set(10, execption);
        set(11, sucess);
        set(12, message);
        set(13, name);
        set(14, transactionId);
        set(15, processstateCompletedstate);
    }
}
