/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables.records;


import com.experts.core.biller.statemachine.api.jooq.tables.Customrevisionentity;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomrevisionentityRecord extends UpdatableRecordImpl<CustomrevisionentityRecord> implements Record8<Long, Timestamp, String, Timestamp, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1108161164;

    /**
     * Setter for <code>public.customrevisionentity.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.customrevisionentity.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.customrevisionentity.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.customrevisionentity.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.customrevisionentity.lastmodifiedby</code>.
     */
    public void setLastmodifiedby(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.customrevisionentity.lastmodifiedby</code>.
     */
    public String getLastmodifiedby() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.customrevisionentity.modifieddate</code>.
     */
    public void setModifieddate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.customrevisionentity.modifieddate</code>.
     */
    public Timestamp getModifieddate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.customrevisionentity.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.customrevisionentity.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.customrevisionentity.login</code>.
     */
    public void setLogin(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.customrevisionentity.login</code>.
     */
    public String getLogin() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.customrevisionentity.customtrackingentity_customid</code>.
     */
    public void setCustomtrackingentityCustomid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.customrevisionentity.customtrackingentity_customid</code>.
     */
    public Integer getCustomtrackingentityCustomid() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.customrevisionentity.customtrackingentity_id</code>.
     */
    public void setCustomtrackingentityId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.customrevisionentity.customtrackingentity_id</code>.
     */
    public Integer getCustomtrackingentityId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Timestamp, String, Timestamp, String, String, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Timestamp, String, Timestamp, String, String, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Customrevisionentity.CUSTOMREVISIONENTITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Customrevisionentity.CUSTOMREVISIONENTITY.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Customrevisionentity.CUSTOMREVISIONENTITY.LASTMODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Customrevisionentity.CUSTOMREVISIONENTITY.MODIFIEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Customrevisionentity.CUSTOMREVISIONENTITY.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Customrevisionentity.CUSTOMREVISIONENTITY.LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Customrevisionentity.CUSTOMREVISIONENTITY.CUSTOMTRACKINGENTITY_CUSTOMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Customrevisionentity.CUSTOMREVISIONENTITY.CUSTOMTRACKINGENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getCustomtrackingentityCustomid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getCustomtrackingentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCustomtrackingentityCustomid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getCustomtrackingentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomrevisionentityRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomrevisionentityRecord value2(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomrevisionentityRecord value3(String value) {
        setLastmodifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomrevisionentityRecord value4(Timestamp value) {
        setModifieddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomrevisionentityRecord value5(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomrevisionentityRecord value6(String value) {
        setLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomrevisionentityRecord value7(Integer value) {
        setCustomtrackingentityCustomid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomrevisionentityRecord value8(Integer value) {
        setCustomtrackingentityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomrevisionentityRecord values(Long value1, Timestamp value2, String value3, Timestamp value4, String value5, String value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomrevisionentityRecord
     */
    public CustomrevisionentityRecord() {
        super(Customrevisionentity.CUSTOMREVISIONENTITY);
    }

    /**
     * Create a detached, initialised CustomrevisionentityRecord
     */
    public CustomrevisionentityRecord(Long id, Timestamp createddate, String lastmodifiedby, Timestamp modifieddate, String username, String login, Integer customtrackingentityCustomid, Integer customtrackingentityId) {
        super(Customrevisionentity.CUSTOMREVISIONENTITY);

        set(0, id);
        set(1, createddate);
        set(2, lastmodifiedby);
        set(3, modifieddate);
        set(4, username);
        set(5, login);
        set(6, customtrackingentityCustomid);
        set(7, customtrackingentityId);
    }
}
