/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables.records;


import com.experts.core.biller.statemachine.api.jooq.tables.PayState;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayStateRecord extends UpdatableRecordImpl<PayStateRecord> implements Record12<Long, Timestamp, String, Timestamp, String, String, String, Integer, String, Integer, Long, Long> {

    private static final long serialVersionUID = -1992361014;

    /**
     * Setter for <code>public.pay_state.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pay_state.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pay_state.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pay_state.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.pay_state.lastmodifiedby</code>.
     */
    public void setLastmodifiedby(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pay_state.lastmodifiedby</code>.
     */
    public String getLastmodifiedby() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.pay_state.modifieddate</code>.
     */
    public void setModifieddate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pay_state.modifieddate</code>.
     */
    public Timestamp getModifieddate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.pay_state.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pay_state.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.pay_state.amount</code>.
     */
    public void setAmount(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pay_state.amount</code>.
     */
    public String getAmount() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.pay_state.bank_code</code>.
     */
    public void setBankCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pay_state.bank_code</code>.
     */
    public String getBankCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.pay_state.currency</code>.
     */
    public void setCurrency(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.pay_state.currency</code>.
     */
    public Integer getCurrency() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.pay_state.transaction</code>.
     */
    public void setTransaction(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.pay_state.transaction</code>.
     */
    public String getTransaction() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.pay_state.version</code>.
     */
    public void setVersion(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.pay_state.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.pay_state.payment_id</code>.
     */
    public void setPaymentId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.pay_state.payment_id</code>.
     */
    public Long getPaymentId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.pay_state.initial_state</code>.
     */
    public void setInitialState(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.pay_state.initial_state</code>.
     */
    public Long getInitialState() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Timestamp, String, Timestamp, String, String, String, Integer, String, Integer, Long, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Timestamp, String, Timestamp, String, String, String, Integer, String, Integer, Long, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PayState.PAY_STATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return PayState.PAY_STATE.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PayState.PAY_STATE.LASTMODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return PayState.PAY_STATE.MODIFIEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PayState.PAY_STATE.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PayState.PAY_STATE.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PayState.PAY_STATE.BANK_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return PayState.PAY_STATE.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return PayState.PAY_STATE.TRANSACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return PayState.PAY_STATE.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return PayState.PAY_STATE.PAYMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return PayState.PAY_STATE.INITIAL_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getBankCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getTransaction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getInitialState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getBankCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getTransaction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getInitialState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value2(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value3(String value) {
        setLastmodifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value4(Timestamp value) {
        setModifieddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value5(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value6(String value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value7(String value) {
        setBankCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value8(Integer value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value9(String value) {
        setTransaction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value10(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value11(Long value) {
        setPaymentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value12(Long value) {
        setInitialState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord values(Long value1, Timestamp value2, String value3, Timestamp value4, String value5, String value6, String value7, Integer value8, String value9, Integer value10, Long value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PayStateRecord
     */
    public PayStateRecord() {
        super(PayState.PAY_STATE);
    }

    /**
     * Create a detached, initialised PayStateRecord
     */
    public PayStateRecord(Long id, Timestamp createddate, String lastmodifiedby, Timestamp modifieddate, String username, String amount, String bankCode, Integer currency, String transaction, Integer version, Long paymentId, Long initialState) {
        super(PayState.PAY_STATE);

        set(0, id);
        set(1, createddate);
        set(2, lastmodifiedby);
        set(3, modifieddate);
        set(4, username);
        set(5, amount);
        set(6, bankCode);
        set(7, currency);
        set(8, transaction);
        set(9, version);
        set(10, paymentId);
        set(11, initialState);
    }
}
