/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables.records;


import com.experts.core.biller.statemachine.api.jooq.tables.TransactionsCreations;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionsCreationsRecord extends UpdatableRecordImpl<TransactionsCreationsRecord> implements Record14<Long, Timestamp, String, Timestamp, String, Timestamp, String, Timestamp, Boolean, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1575539361;

    /**
     * Setter for <code>public.transactions_creations.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.transactions_creations.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.transactions_creations.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.transactions_creations.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.transactions_creations.lastmodifiedby</code>.
     */
    public void setLastmodifiedby(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.transactions_creations.lastmodifiedby</code>.
     */
    public String getLastmodifiedby() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.transactions_creations.modifieddate</code>.
     */
    public void setModifieddate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.transactions_creations.modifieddate</code>.
     */
    public Timestamp getModifieddate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.transactions_creations.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.transactions_creations.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.transactions_creations.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.transactions_creations.creation_date</code>.
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.transactions_creations.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.transactions_creations.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.transactions_creations.exception_date</code>.
     */
    public void setExceptionDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.transactions_creations.exception_date</code>.
     */
    public Timestamp getExceptionDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.transactions_creations.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.transactions_creations.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.transactions_creations.request</code>.
     */
    public void setRequest(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.transactions_creations.request</code>.
     */
    public String getRequest() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.transactions_creations.response</code>.
     */
    public void setResponse(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.transactions_creations.response</code>.
     */
    public String getResponse() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.transactions_creations.serial_no</code>.
     */
    public void setSerialNo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.transactions_creations.serial_no</code>.
     */
    public String getSerialNo() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.transactions_creations.op_type</code>.
     */
    public void setOpType(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.transactions_creations.op_type</code>.
     */
    public Integer getOpType() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.transactions_creations.version</code>.
     */
    public void setVersion(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.transactions_creations.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Timestamp, String, Timestamp, String, Timestamp, String, Timestamp, Boolean, String, String, String, Integer, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Timestamp, String, Timestamp, String, Timestamp, String, Timestamp, Boolean, String, String, String, Integer, Integer> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.LASTMODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.MODIFIEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.EXCEPTION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.SUCCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.REQUEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.RESPONSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.SERIAL_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.OP_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return TransactionsCreations.TRANSACTIONS_CREATIONS.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getExceptionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getSuccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getRequest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getResponse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getSerialNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getOpType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastmodifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getExceptionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getSuccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRequest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getResponse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getSerialNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getOpType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value2(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value3(String value) {
        setLastmodifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value4(Timestamp value) {
        setModifieddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value5(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value6(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value8(Timestamp value) {
        setExceptionDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value9(Boolean value) {
        setSuccess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value10(String value) {
        setRequest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value11(String value) {
        setResponse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value12(String value) {
        setSerialNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value13(Integer value) {
        setOpType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord value14(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionsCreationsRecord values(Long value1, Timestamp value2, String value3, Timestamp value4, String value5, Timestamp value6, String value7, Timestamp value8, Boolean value9, String value10, String value11, String value12, Integer value13, Integer value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionsCreationsRecord
     */
    public TransactionsCreationsRecord() {
        super(TransactionsCreations.TRANSACTIONS_CREATIONS);
    }

    /**
     * Create a detached, initialised TransactionsCreationsRecord
     */
    public TransactionsCreationsRecord(Long id, Timestamp createddate, String lastmodifiedby, Timestamp modifieddate, String username, Timestamp creationDate, String description, Timestamp exceptionDate, Boolean success, String request, String response, String serialNo, Integer opType, Integer version) {
        super(TransactionsCreations.TRANSACTIONS_CREATIONS);

        set(0, id);
        set(1, createddate);
        set(2, lastmodifiedby);
        set(3, modifieddate);
        set(4, username);
        set(5, creationDate);
        set(6, description);
        set(7, exceptionDate);
        set(8, success);
        set(9, request);
        set(10, response);
        set(11, serialNo);
        set(12, opType);
        set(13, version);
    }
}
