/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables.records;


import com.experts.core.biller.statemachine.api.jooq.tables.UserAuthorities;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAuthoritiesRecord extends TableRecordImpl<UserAuthoritiesRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -2123492497;

    /**
     * Setter for <code>public.user_authorities.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_authorities.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_authorities.authority_id</code>.
     */
    public void setAuthorityId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_authorities.authority_id</code>.
     */
    public Long getAuthorityId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UserAuthorities.USER_AUTHORITIES.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return UserAuthorities.USER_AUTHORITIES.AUTHORITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAuthorityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAuthorityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAuthoritiesRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAuthoritiesRecord value2(Long value) {
        setAuthorityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAuthoritiesRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAuthoritiesRecord
     */
    public UserAuthoritiesRecord() {
        super(UserAuthorities.USER_AUTHORITIES);
    }

    /**
     * Create a detached, initialised UserAuthoritiesRecord
     */
    public UserAuthoritiesRecord(Long userId, Long authorityId) {
        super(UserAuthorities.USER_AUTHORITIES);

        set(0, userId);
        set(1, authorityId);
    }
}
