/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq;


import com.experts.core.biller.statemachine.api.jooq.tables.AccountDetails;
import com.experts.core.biller.statemachine.api.jooq.tables.AccountType;
import com.experts.core.biller.statemachine.api.jooq.tables.Authorities;
import com.experts.core.biller.statemachine.api.jooq.tables.BankDetails;
import com.experts.core.biller.statemachine.api.jooq.tables.BankServiceCatogery;
import com.experts.core.biller.statemachine.api.jooq.tables.BankServiceCatogeryType;
import com.experts.core.biller.statemachine.api.jooq.tables.BankServices;
import com.experts.core.biller.statemachine.api.jooq.tables.BillCreationHistory;
import com.experts.core.biller.statemachine.api.jooq.tables.BillPullRequest;
import com.experts.core.biller.statemachine.api.jooq.tables.BillerApiIntegrations;
import com.experts.core.biller.statemachine.api.jooq.tables.BillerServiceCatogrey;
import com.experts.core.biller.statemachine.api.jooq.tables.Billingcreation;
import com.experts.core.biller.statemachine.api.jooq.tables.CompletedState;
import com.experts.core.biller.statemachine.api.jooq.tables.ConfigurationBiller;
import com.experts.core.biller.statemachine.api.jooq.tables.Customer;
import com.experts.core.biller.statemachine.api.jooq.tables.Customrevisionentity;
import com.experts.core.biller.statemachine.api.jooq.tables.Customtrackingentity;
import com.experts.core.biller.statemachine.api.jooq.tables.EmployeeDetails;
import com.experts.core.biller.statemachine.api.jooq.tables.InitialState;
import com.experts.core.biller.statemachine.api.jooq.tables.InquiryBillCurrent;
import com.experts.core.biller.statemachine.api.jooq.tables.InquiryHistory;
import com.experts.core.biller.statemachine.api.jooq.tables.MuleEsbIntegration;
import com.experts.core.biller.statemachine.api.jooq.tables.PayState;
import com.experts.core.biller.statemachine.api.jooq.tables.PaymentStatus;
import com.experts.core.biller.statemachine.api.jooq.tables.Payments;
import com.experts.core.biller.statemachine.api.jooq.tables.ProcessState;
import com.experts.core.biller.statemachine.api.jooq.tables.RolesAuth;
import com.experts.core.biller.statemachine.api.jooq.tables.SystemLog;
import com.experts.core.biller.statemachine.api.jooq.tables.SystemSettings;
import com.experts.core.biller.statemachine.api.jooq.tables.SystemSettingsCatogrey;
import com.experts.core.biller.statemachine.api.jooq.tables.Tasks;
import com.experts.core.biller.statemachine.api.jooq.tables.TasksVarible;
import com.experts.core.biller.statemachine.api.jooq.tables.Transaction;
import com.experts.core.biller.statemachine.api.jooq.tables.TransactionBatchJob;
import com.experts.core.biller.statemachine.api.jooq.tables.TransactionQueue;
import com.experts.core.biller.statemachine.api.jooq.tables.TransactionThreadCapcity;
import com.experts.core.biller.statemachine.api.jooq.tables.TransactionsApproved;
import com.experts.core.biller.statemachine.api.jooq.tables.TransactionsCreations;
import com.experts.core.biller.statemachine.api.jooq.tables.Transactionstatus;
import com.experts.core.biller.statemachine.api.jooq.tables.Users;
import com.experts.core.biller.statemachine.api.jooq.tables.Users_;
import com.experts.core.biller.statemachine.api.jooq.tables.WaitingState;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_DETAILS_PKEY = Indexes0.ACCOUNT_DETAILS_PKEY;
    public static final Index ACCOUNT_TYPE_PKEY = Indexes0.ACCOUNT_TYPE_PKEY;
    public static final Index AUTHORITIES_PKEY = Indexes0.AUTHORITIES_PKEY;
    public static final Index UK_Q0U5F2CDLSHEC8TLH6818BHBK = Indexes0.UK_Q0U5F2CDLSHEC8TLH6818BHBK;
    public static final Index BANK_DETAILS_PKEY = Indexes0.BANK_DETAILS_PKEY;
    public static final Index BANK_SERVICE_CATOGERY_PKEY = Indexes0.BANK_SERVICE_CATOGERY_PKEY;
    public static final Index BANK_SERVICE_CATOGERY_TYPE_PKEY = Indexes0.BANK_SERVICE_CATOGERY_TYPE_PKEY;
    public static final Index BANK_SERVICES_PKEY = Indexes0.BANK_SERVICES_PKEY;
    public static final Index BILL_CREATION_HISTORY_PKEY = Indexes0.BILL_CREATION_HISTORY_PKEY;
    public static final Index BILL_PULL_REQUEST_PKEY = Indexes0.BILL_PULL_REQUEST_PKEY;
    public static final Index BILLER_API_INTEGRATIONS_PKEY = Indexes0.BILLER_API_INTEGRATIONS_PKEY;
    public static final Index BILLER_SERVICE_CATOGREY_PKEY = Indexes0.BILLER_SERVICE_CATOGREY_PKEY;
    public static final Index BILLINGCREATION_PKEY = Indexes0.BILLINGCREATION_PKEY;
    public static final Index COMPLETED_STATE_PKEY = Indexes0.COMPLETED_STATE_PKEY;
    public static final Index CONFIGURATION_BILLER_PKEY = Indexes0.CONFIGURATION_BILLER_PKEY;
    public static final Index CUSTOMER_PKEY = Indexes0.CUSTOMER_PKEY;
    public static final Index CUSTOMREVISIONENTITY_PKEY = Indexes0.CUSTOMREVISIONENTITY_PKEY;
    public static final Index CUSTOMTRACKINGENTITY_PKEY = Indexes0.CUSTOMTRACKINGENTITY_PKEY;
    public static final Index EMPLOYEE_DETAILS_PKEY = Indexes0.EMPLOYEE_DETAILS_PKEY;
    public static final Index INITIAL_STATE_PKEY = Indexes0.INITIAL_STATE_PKEY;
    public static final Index INQUIRY_BILL_CURRENT_PKEY = Indexes0.INQUIRY_BILL_CURRENT_PKEY;
    public static final Index INQUIRY_HISTORY_PKEY = Indexes0.INQUIRY_HISTORY_PKEY;
    public static final Index MULE_ESB_INTEGRATION_PKEY = Indexes0.MULE_ESB_INTEGRATION_PKEY;
    public static final Index PAY_STATE_PKEY = Indexes0.PAY_STATE_PKEY;
    public static final Index PAYMENT_STATUS_PKEY = Indexes0.PAYMENT_STATUS_PKEY;
    public static final Index PAYMENTS_PKEY = Indexes0.PAYMENTS_PKEY;
    public static final Index PROCESS_STATE_PKEY = Indexes0.PROCESS_STATE_PKEY;
    public static final Index ROLES_AUTH_PKEY = Indexes0.ROLES_AUTH_PKEY;
    public static final Index UK_SO8W80GEK2HHOIWQEUU6P8E6 = Indexes0.UK_SO8W80GEK2HHOIWQEUU6P8E6;
    public static final Index SYSTEM_LOG_PKEY = Indexes0.SYSTEM_LOG_PKEY;
    public static final Index SYSTEM_SETTINGS_PKEY = Indexes0.SYSTEM_SETTINGS_PKEY;
    public static final Index SYSTEM_SETTINGS_CATOGREY_PKEY = Indexes0.SYSTEM_SETTINGS_CATOGREY_PKEY;
    public static final Index TASKS_PKEY = Indexes0.TASKS_PKEY;
    public static final Index TASKS_VARIBLE_PKEY = Indexes0.TASKS_VARIBLE_PKEY;
    public static final Index TRANSACTION_PKEY = Indexes0.TRANSACTION_PKEY;
    public static final Index TRANSACTION_BATCH_JOB_PKEY = Indexes0.TRANSACTION_BATCH_JOB_PKEY;
    public static final Index TRANSACTION_QUEUE_PKEY = Indexes0.TRANSACTION_QUEUE_PKEY;
    public static final Index TRANSACTION_THREAD_CAPCITY_PKEY = Indexes0.TRANSACTION_THREAD_CAPCITY_PKEY;
    public static final Index TRANSACTIONS_APPROVED_PKEY = Indexes0.TRANSACTIONS_APPROVED_PKEY;
    public static final Index TRANSACTIONS_CREATIONS_PKEY = Indexes0.TRANSACTIONS_CREATIONS_PKEY;
    public static final Index TRANSACTIONSTATUS_PKEY = Indexes0.TRANSACTIONSTATUS_PKEY;
    public static final Index UK_3G1J96G94XPK3LPXL2QBL985X = Indexes0.UK_3G1J96G94XPK3LPXL2QBL985X;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;
    public static final Index USERS__PKEY = Indexes0.USERS__PKEY;
    public static final Index WAITING_STATE_PKEY = Indexes0.WAITING_STATE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_DETAILS_PKEY = Internal.createIndex("account_details_pkey", AccountDetails.ACCOUNT_DETAILS, new OrderField[] { AccountDetails.ACCOUNT_DETAILS.ID }, true);
        public static Index ACCOUNT_TYPE_PKEY = Internal.createIndex("account_type_pkey", AccountType.ACCOUNT_TYPE, new OrderField[] { AccountType.ACCOUNT_TYPE.ID }, true);
        public static Index AUTHORITIES_PKEY = Internal.createIndex("authorities_pkey", Authorities.AUTHORITIES, new OrderField[] { Authorities.AUTHORITIES.ID }, true);
        public static Index UK_Q0U5F2CDLSHEC8TLH6818BHBK = Internal.createIndex("uk_q0u5f2cdlshec8tlh6818bhbk", Authorities.AUTHORITIES, new OrderField[] { Authorities.AUTHORITIES.AUTHORITY }, true);
        public static Index BANK_DETAILS_PKEY = Internal.createIndex("bank_details_pkey", BankDetails.BANK_DETAILS, new OrderField[] { BankDetails.BANK_DETAILS.ID }, true);
        public static Index BANK_SERVICE_CATOGERY_PKEY = Internal.createIndex("bank_service_catogery_pkey", BankServiceCatogery.BANK_SERVICE_CATOGERY, new OrderField[] { BankServiceCatogery.BANK_SERVICE_CATOGERY.ID }, true);
        public static Index BANK_SERVICE_CATOGERY_TYPE_PKEY = Internal.createIndex("bank_service_catogery_type_pkey", BankServiceCatogeryType.BANK_SERVICE_CATOGERY_TYPE, new OrderField[] { BankServiceCatogeryType.BANK_SERVICE_CATOGERY_TYPE.ID }, true);
        public static Index BANK_SERVICES_PKEY = Internal.createIndex("bank_services_pkey", BankServices.BANK_SERVICES, new OrderField[] { BankServices.BANK_SERVICES.ID }, true);
        public static Index BILL_CREATION_HISTORY_PKEY = Internal.createIndex("bill_creation_history_pkey", BillCreationHistory.BILL_CREATION_HISTORY, new OrderField[] { BillCreationHistory.BILL_CREATION_HISTORY.ID }, true);
        public static Index BILL_PULL_REQUEST_PKEY = Internal.createIndex("bill_pull_request_pkey", BillPullRequest.BILL_PULL_REQUEST, new OrderField[] { BillPullRequest.BILL_PULL_REQUEST.ID }, true);
        public static Index BILLER_API_INTEGRATIONS_PKEY = Internal.createIndex("biller_api_integrations_pkey", BillerApiIntegrations.BILLER_API_INTEGRATIONS, new OrderField[] { BillerApiIntegrations.BILLER_API_INTEGRATIONS.ID }, true);
        public static Index BILLER_SERVICE_CATOGREY_PKEY = Internal.createIndex("biller_service_catogrey_pkey", BillerServiceCatogrey.BILLER_SERVICE_CATOGREY, new OrderField[] { BillerServiceCatogrey.BILLER_SERVICE_CATOGREY.ID }, true);
        public static Index BILLINGCREATION_PKEY = Internal.createIndex("billingcreation_pkey", Billingcreation.BILLINGCREATION, new OrderField[] { Billingcreation.BILLINGCREATION.ID }, true);
        public static Index COMPLETED_STATE_PKEY = Internal.createIndex("completed_state_pkey", CompletedState.COMPLETED_STATE, new OrderField[] { CompletedState.COMPLETED_STATE.ID }, true);
        public static Index CONFIGURATION_BILLER_PKEY = Internal.createIndex("configuration_biller_pkey", ConfigurationBiller.CONFIGURATION_BILLER, new OrderField[] { ConfigurationBiller.CONFIGURATION_BILLER.ID }, true);
        public static Index CUSTOMER_PKEY = Internal.createIndex("customer_pkey", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
        public static Index CUSTOMREVISIONENTITY_PKEY = Internal.createIndex("customrevisionentity_pkey", Customrevisionentity.CUSTOMREVISIONENTITY, new OrderField[] { Customrevisionentity.CUSTOMREVISIONENTITY.ID }, true);
        public static Index CUSTOMTRACKINGENTITY_PKEY = Internal.createIndex("customtrackingentity_pkey", Customtrackingentity.CUSTOMTRACKINGENTITY, new OrderField[] { Customtrackingentity.CUSTOMTRACKINGENTITY.CUSTOMID, Customtrackingentity.CUSTOMTRACKINGENTITY.ID }, true);
        public static Index EMPLOYEE_DETAILS_PKEY = Internal.createIndex("employee_details_pkey", EmployeeDetails.EMPLOYEE_DETAILS, new OrderField[] { EmployeeDetails.EMPLOYEE_DETAILS.ID }, true);
        public static Index INITIAL_STATE_PKEY = Internal.createIndex("initial_state_pkey", InitialState.INITIAL_STATE, new OrderField[] { InitialState.INITIAL_STATE.ID }, true);
        public static Index INQUIRY_BILL_CURRENT_PKEY = Internal.createIndex("inquiry_bill_current_pkey", InquiryBillCurrent.INQUIRY_BILL_CURRENT, new OrderField[] { InquiryBillCurrent.INQUIRY_BILL_CURRENT.ID }, true);
        public static Index INQUIRY_HISTORY_PKEY = Internal.createIndex("inquiry_history_pkey", InquiryHistory.INQUIRY_HISTORY, new OrderField[] { InquiryHistory.INQUIRY_HISTORY.ID }, true);
        public static Index MULE_ESB_INTEGRATION_PKEY = Internal.createIndex("mule_esb_integration_pkey", MuleEsbIntegration.MULE_ESB_INTEGRATION, new OrderField[] { MuleEsbIntegration.MULE_ESB_INTEGRATION.ID }, true);
        public static Index PAY_STATE_PKEY = Internal.createIndex("pay_state_pkey", PayState.PAY_STATE, new OrderField[] { PayState.PAY_STATE.ID }, true);
        public static Index PAYMENT_STATUS_PKEY = Internal.createIndex("payment_status_pkey", PaymentStatus.PAYMENT_STATUS, new OrderField[] { PaymentStatus.PAYMENT_STATUS.ID }, true);
        public static Index PAYMENTS_PKEY = Internal.createIndex("payments_pkey", Payments.PAYMENTS, new OrderField[] { Payments.PAYMENTS.ID }, true);
        public static Index PROCESS_STATE_PKEY = Internal.createIndex("process_state_pkey", ProcessState.PROCESS_STATE, new OrderField[] { ProcessState.PROCESS_STATE.ID }, true);
        public static Index ROLES_AUTH_PKEY = Internal.createIndex("roles_auth_pkey", RolesAuth.ROLES_AUTH, new OrderField[] { RolesAuth.ROLES_AUTH.ID }, true);
        public static Index UK_SO8W80GEK2HHOIWQEUU6P8E6 = Internal.createIndex("uk_so8w80gek2hhoiwqeuu6p8e6", RolesAuth.ROLES_AUTH, new OrderField[] { RolesAuth.ROLES_AUTH.AUTH }, true);
        public static Index SYSTEM_LOG_PKEY = Internal.createIndex("system_log_pkey", SystemLog.SYSTEM_LOG, new OrderField[] { SystemLog.SYSTEM_LOG.ID }, true);
        public static Index SYSTEM_SETTINGS_PKEY = Internal.createIndex("system_settings_pkey", SystemSettings.SYSTEM_SETTINGS, new OrderField[] { SystemSettings.SYSTEM_SETTINGS.ID }, true);
        public static Index SYSTEM_SETTINGS_CATOGREY_PKEY = Internal.createIndex("system_settings_catogrey_pkey", SystemSettingsCatogrey.SYSTEM_SETTINGS_CATOGREY, new OrderField[] { SystemSettingsCatogrey.SYSTEM_SETTINGS_CATOGREY.ID }, true);
        public static Index TASKS_PKEY = Internal.createIndex("tasks_pkey", Tasks.TASKS, new OrderField[] { Tasks.TASKS.ID }, true);
        public static Index TASKS_VARIBLE_PKEY = Internal.createIndex("tasks_varible_pkey", TasksVarible.TASKS_VARIBLE, new OrderField[] { TasksVarible.TASKS_VARIBLE.ID }, true);
        public static Index TRANSACTION_PKEY = Internal.createIndex("transaction_pkey", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.ID }, true);
        public static Index TRANSACTION_BATCH_JOB_PKEY = Internal.createIndex("transaction_batch_job_pkey", TransactionBatchJob.TRANSACTION_BATCH_JOB, new OrderField[] { TransactionBatchJob.TRANSACTION_BATCH_JOB.ID }, true);
        public static Index TRANSACTION_QUEUE_PKEY = Internal.createIndex("transaction_queue_pkey", TransactionQueue.TRANSACTION_QUEUE, new OrderField[] { TransactionQueue.TRANSACTION_QUEUE.ID }, true);
        public static Index TRANSACTION_THREAD_CAPCITY_PKEY = Internal.createIndex("transaction_thread_capcity_pkey", TransactionThreadCapcity.TRANSACTION_THREAD_CAPCITY, new OrderField[] { TransactionThreadCapcity.TRANSACTION_THREAD_CAPCITY.ID }, true);
        public static Index TRANSACTIONS_APPROVED_PKEY = Internal.createIndex("transactions_approved_pkey", TransactionsApproved.TRANSACTIONS_APPROVED, new OrderField[] { TransactionsApproved.TRANSACTIONS_APPROVED.ID }, true);
        public static Index TRANSACTIONS_CREATIONS_PKEY = Internal.createIndex("transactions_creations_pkey", TransactionsCreations.TRANSACTIONS_CREATIONS, new OrderField[] { TransactionsCreations.TRANSACTIONS_CREATIONS.ID }, true);
        public static Index TRANSACTIONSTATUS_PKEY = Internal.createIndex("transactionstatus_pkey", Transactionstatus.TRANSACTIONSTATUS, new OrderField[] { Transactionstatus.TRANSACTIONSTATUS.ID }, true);
        public static Index UK_3G1J96G94XPK3LPXL2QBL985X = Internal.createIndex("uk_3g1j96g94xpk3lpxl2qbl985x", Users.USERS, new OrderField[] { Users.USERS.NAME }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS__PKEY = Internal.createIndex("users__pkey", Users_.USERS_, new OrderField[] { Users_.USERS_.ID }, true);
        public static Index WAITING_STATE_PKEY = Internal.createIndex("waiting_state_pkey", WaitingState.WAITING_STATE, new OrderField[] { WaitingState.WAITING_STATE.ID }, true);
    }
}
