/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.model.jooq.tables;


import com.experts.core.biller.statemachine.api.model.jooq.Indexes;
import com.experts.core.biller.statemachine.api.model.jooq.Keys;
import com.experts.core.biller.statemachine.api.model.jooq.Public;
import com.experts.core.biller.statemachine.api.model.jooq.tables.records.BillCreationHistoryRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BillCreationHistory extends TableImpl<BillCreationHistoryRecord> {

    private static final long serialVersionUID = -475131371;

    /**
     * The reference instance of <code>public.bill_creation_history</code>
     */
    public static final BillCreationHistory BILL_CREATION_HISTORY = new BillCreationHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BillCreationHistoryRecord> getRecordType() {
        return BillCreationHistoryRecord.class;
    }

    /**
     * The column <code>public.bill_creation_history.id</code>.
     */
    public final TableField<BillCreationHistoryRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.bill_creation_history.createddate</code>.
     */
    public final TableField<BillCreationHistoryRecord, Timestamp> CREATEDDATE = createField("createddate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.bill_creation_history.modifieddate</code>.
     */
    public final TableField<BillCreationHistoryRecord, Timestamp> MODIFIEDDATE = createField("modifieddate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.bill_creation_history.username</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.bankaddress</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> BANKADDRESS = createField("bankaddress", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.bankcode</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> BANKCODE = createField("bankcode", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.bankid</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> BANKID = createField("bankid", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.bankname</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> BANKNAME = createField("bankname", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.billcode</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> BILLCODE = createField("billcode", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.billname</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> BILLNAME = createField("billname", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.billeraddress</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> BILLERADDRESS = createField("billeraddress", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.billercode</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> BILLERCODE = createField("billercode", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.billername</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> BILLERNAME = createField("billername", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.clientid</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> CLIENTID = createField("clientid", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.bill_creation_history.onserviceby</code>.
     */
    public final TableField<BillCreationHistoryRecord, String> ONSERVICEBY = createField("onserviceby", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>public.bill_creation_history</code> table reference
     */
    public BillCreationHistory() {
        this(DSL.name("bill_creation_history"), null);
    }

    /**
     * Create an aliased <code>public.bill_creation_history</code> table reference
     */
    public BillCreationHistory(String alias) {
        this(DSL.name(alias), BILL_CREATION_HISTORY);
    }

    /**
     * Create an aliased <code>public.bill_creation_history</code> table reference
     */
    public BillCreationHistory(Name alias) {
        this(alias, BILL_CREATION_HISTORY);
    }

    private BillCreationHistory(Name alias, Table<BillCreationHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private BillCreationHistory(Name alias, Table<BillCreationHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BillCreationHistory(Table<O> child, ForeignKey<O, BillCreationHistoryRecord> key) {
        super(child, key, BILL_CREATION_HISTORY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BILL_CREATION_HISTORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BillCreationHistoryRecord> getPrimaryKey() {
        return Keys.BILL_CREATION_HISTORY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BillCreationHistoryRecord>> getKeys() {
        return Arrays.<UniqueKey<BillCreationHistoryRecord>>asList(Keys.BILL_CREATION_HISTORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillCreationHistory as(String alias) {
        return new BillCreationHistory(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillCreationHistory as(Name alias) {
        return new BillCreationHistory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BillCreationHistory rename(String name) {
        return new BillCreationHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BillCreationHistory rename(Name name) {
        return new BillCreationHistory(name, null);
    }
}
