/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.model.jooq.tables;


import com.experts.core.biller.statemachine.api.model.jooq.Indexes;
import com.experts.core.biller.statemachine.api.model.jooq.Keys;
import com.experts.core.biller.statemachine.api.model.jooq.Public;
import com.experts.core.biller.statemachine.api.model.jooq.tables.records.InquiryHistoryRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryHistory extends TableImpl<InquiryHistoryRecord> {

    private static final long serialVersionUID = 732312245;

    /**
     * The reference instance of <code>public.inquiry_history</code>
     */
    public static final InquiryHistory INQUIRY_HISTORY = new InquiryHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InquiryHistoryRecord> getRecordType() {
        return InquiryHistoryRecord.class;
    }

    /**
     * The column <code>public.inquiry_history.id</code>.
     */
    public final TableField<InquiryHistoryRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.inquiry_history.createddate</code>.
     */
    public final TableField<InquiryHistoryRecord, Timestamp> CREATEDDATE = createField("createddate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.inquiry_history.modifieddate</code>.
     */
    public final TableField<InquiryHistoryRecord, Timestamp> MODIFIEDDATE = createField("modifieddate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.inquiry_history.username</code>.
     */
    public final TableField<InquiryHistoryRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.bankaddress</code>.
     */
    public final TableField<InquiryHistoryRecord, String> BANKADDRESS = createField("bankaddress", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.bankcode</code>.
     */
    public final TableField<InquiryHistoryRecord, String> BANKCODE = createField("bankcode", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.bankid</code>.
     */
    public final TableField<InquiryHistoryRecord, String> BANKID = createField("bankid", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.bankname</code>.
     */
    public final TableField<InquiryHistoryRecord, String> BANKNAME = createField("bankname", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.billcode</code>.
     */
    public final TableField<InquiryHistoryRecord, String> BILLCODE = createField("billcode", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.billname</code>.
     */
    public final TableField<InquiryHistoryRecord, String> BILLNAME = createField("billname", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.billeraddress</code>.
     */
    public final TableField<InquiryHistoryRecord, String> BILLERADDRESS = createField("billeraddress", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.billercode</code>.
     */
    public final TableField<InquiryHistoryRecord, String> BILLERCODE = createField("billercode", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.billername</code>.
     */
    public final TableField<InquiryHistoryRecord, String> BILLERNAME = createField("billername", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.clientid</code>.
     */
    public final TableField<InquiryHistoryRecord, String> CLIENTID = createField("clientid", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.inquiry_history.onserviceby</code>.
     */
    public final TableField<InquiryHistoryRecord, String> ONSERVICEBY = createField("onserviceby", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>public.inquiry_history</code> table reference
     */
    public InquiryHistory() {
        this(DSL.name("inquiry_history"), null);
    }

    /**
     * Create an aliased <code>public.inquiry_history</code> table reference
     */
    public InquiryHistory(String alias) {
        this(DSL.name(alias), INQUIRY_HISTORY);
    }

    /**
     * Create an aliased <code>public.inquiry_history</code> table reference
     */
    public InquiryHistory(Name alias) {
        this(alias, INQUIRY_HISTORY);
    }

    private InquiryHistory(Name alias, Table<InquiryHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private InquiryHistory(Name alias, Table<InquiryHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> InquiryHistory(Table<O> child, ForeignKey<O, InquiryHistoryRecord> key) {
        super(child, key, INQUIRY_HISTORY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INQUIRY_HISTORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InquiryHistoryRecord> getPrimaryKey() {
        return Keys.INQUIRY_HISTORY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InquiryHistoryRecord>> getKeys() {
        return Arrays.<UniqueKey<InquiryHistoryRecord>>asList(Keys.INQUIRY_HISTORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryHistory as(String alias) {
        return new InquiryHistory(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryHistory as(Name alias) {
        return new InquiryHistory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InquiryHistory rename(String name) {
        return new InquiryHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InquiryHistory rename(Name name) {
        return new InquiryHistory(name, null);
    }
}
