/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.model.jooq.tables.records;


import com.experts.core.biller.statemachine.api.model.jooq.tables.ModifiedEntity;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModifiedEntityRecord extends UpdatableRecordImpl<ModifiedEntityRecord> implements Record3<String, String, Integer> {

    private static final long serialVersionUID = 521945820;

    /**
     * Setter for <code>public.modified_entity.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.modified_entity.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.modified_entity.entity_cls_name</code>.
     */
    public void setEntityClsName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.modified_entity.entity_cls_name</code>.
     */
    public String getEntityClsName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.modified_entity.revision_id</code>.
     */
    public void setRevisionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.modified_entity.revision_id</code>.
     */
    public Integer getRevisionId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ModifiedEntity.MODIFIED_ENTITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ModifiedEntity.MODIFIED_ENTITY.ENTITY_CLS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ModifiedEntity.MODIFIED_ENTITY.REVISION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEntityClsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRevisionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEntityClsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRevisionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModifiedEntityRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModifiedEntityRecord value2(String value) {
        setEntityClsName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModifiedEntityRecord value3(Integer value) {
        setRevisionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModifiedEntityRecord values(String value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModifiedEntityRecord
     */
    public ModifiedEntityRecord() {
        super(ModifiedEntity.MODIFIED_ENTITY);
    }

    /**
     * Create a detached, initialised ModifiedEntityRecord
     */
    public ModifiedEntityRecord(String id, String entityClsName, Integer revisionId) {
        super(ModifiedEntity.MODIFIED_ENTITY);

        set(0, id);
        set(1, entityClsName);
        set(2, revisionId);
    }
}
