/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.model.jooq.tables.records;


import com.experts.core.biller.statemachine.api.model.jooq.tables.PayState;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayStateRecord extends UpdatableRecordImpl<PayStateRecord> implements Record9<Long, Timestamp, Timestamp, String, String, String, Integer, String, Long> {

    private static final long serialVersionUID = 2024664249;

    /**
     * Setter for <code>public.pay_state.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pay_state.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pay_state.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pay_state.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.pay_state.modifieddate</code>.
     */
    public void setModifieddate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pay_state.modifieddate</code>.
     */
    public Timestamp getModifieddate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.pay_state.username</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pay_state.username</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.pay_state.amount</code>.
     */
    public void setAmount(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pay_state.amount</code>.
     */
    public String getAmount() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.pay_state.bank_code</code>.
     */
    public void setBankCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pay_state.bank_code</code>.
     */
    public String getBankCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.pay_state.currency</code>.
     */
    public void setCurrency(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pay_state.currency</code>.
     */
    public Integer getCurrency() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.pay_state.transaction</code>.
     */
    public void setTransaction(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.pay_state.transaction</code>.
     */
    public String getTransaction() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.pay_state.initial_state</code>.
     */
    public void setInitialState(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.pay_state.initial_state</code>.
     */
    public Long getInitialState() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Timestamp, Timestamp, String, String, String, Integer, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Timestamp, Timestamp, String, String, String, Integer, String, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PayState.PAY_STATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return PayState.PAY_STATE.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return PayState.PAY_STATE.MODIFIEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PayState.PAY_STATE.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PayState.PAY_STATE.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PayState.PAY_STATE.BANK_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return PayState.PAY_STATE.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return PayState.PAY_STATE.TRANSACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return PayState.PAY_STATE.INITIAL_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getBankCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getTransaction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getInitialState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getBankCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTransaction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getInitialState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value2(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value3(Timestamp value) {
        setModifieddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value4(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value5(String value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value6(String value) {
        setBankCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value7(Integer value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value8(String value) {
        setTransaction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord value9(Long value) {
        setInitialState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayStateRecord values(Long value1, Timestamp value2, Timestamp value3, String value4, String value5, String value6, Integer value7, String value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PayStateRecord
     */
    public PayStateRecord() {
        super(PayState.PAY_STATE);
    }

    /**
     * Create a detached, initialised PayStateRecord
     */
    public PayStateRecord(Long id, Timestamp createddate, Timestamp modifieddate, String username, String amount, String bankCode, Integer currency, String transaction, Long initialState) {
        super(PayState.PAY_STATE);

        set(0, id);
        set(1, createddate);
        set(2, modifieddate);
        set(3, username);
        set(4, amount);
        set(5, bankCode);
        set(6, currency);
        set(7, transaction);
        set(8, initialState);
    }
}
