/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables;


import com.experts.core.biller.statemachine.api.jooq.Indexes;
import com.experts.core.biller.statemachine.api.jooq.Keys;
import com.experts.core.biller.statemachine.api.jooq.Public;
import com.experts.core.biller.statemachine.api.jooq.tables.records.AccountDetailsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountDetails extends TableImpl<AccountDetailsRecord> {

    private static final long serialVersionUID = 752357105;

    /**
     * The reference instance of <code>public.account_details</code>
     */
    public static final AccountDetails ACCOUNT_DETAILS = new AccountDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountDetailsRecord> getRecordType() {
        return AccountDetailsRecord.class;
    }

    /**
     * The column <code>public.account_details.id</code>.
     */
    public final TableField<AccountDetailsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.account_details.createddate</code>.
     */
    public final TableField<AccountDetailsRecord, Timestamp> CREATEDDATE = createField("createddate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.account_details.lastmodifiedby</code>.
     */
    public final TableField<AccountDetailsRecord, String> LASTMODIFIEDBY = createField("lastmodifiedby", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.account_details.modifieddate</code>.
     */
    public final TableField<AccountDetailsRecord, Timestamp> MODIFIEDDATE = createField("modifieddate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.account_details.username</code>.
     */
    public final TableField<AccountDetailsRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.account_details.account_name</code>.
     */
    public final TableField<AccountDetailsRecord, String> ACCOUNT_NAME = createField("account_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.account_details.account_number</code>.
     */
    public final TableField<AccountDetailsRecord, String> ACCOUNT_NUMBER = createField("account_number", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.account_details.balance</code>.
     */
    public final TableField<AccountDetailsRecord, Integer> BALANCE = createField("balance", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.account_details.isbn</code>.
     */
    public final TableField<AccountDetailsRecord, String> ISBN = createField("isbn", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.account_details.max_queue_tx</code>.
     */
    public final TableField<AccountDetailsRecord, Integer> MAX_QUEUE_TX = createField("max_queue_tx", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.account_details.maxtx</code>.
     */
    public final TableField<AccountDetailsRecord, Integer> MAXTX = createField("maxtx", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.account_details.version</code>.
     */
    public final TableField<AccountDetailsRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.account_details</code> table reference
     */
    public AccountDetails() {
        this(DSL.name("account_details"), null);
    }

    /**
     * Create an aliased <code>public.account_details</code> table reference
     */
    public AccountDetails(String alias) {
        this(DSL.name(alias), ACCOUNT_DETAILS);
    }

    /**
     * Create an aliased <code>public.account_details</code> table reference
     */
    public AccountDetails(Name alias) {
        this(alias, ACCOUNT_DETAILS);
    }

    private AccountDetails(Name alias, Table<AccountDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AccountDetails(Name alias, Table<AccountDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AccountDetails(Table<O> child, ForeignKey<O, AccountDetailsRecord> key) {
        super(child, key, ACCOUNT_DETAILS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACCOUNT_DETAILS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AccountDetailsRecord> getPrimaryKey() {
        return Keys.ACCOUNT_DETAILS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AccountDetailsRecord>> getKeys() {
        return Arrays.<UniqueKey<AccountDetailsRecord>>asList(Keys.ACCOUNT_DETAILS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetails as(String alias) {
        return new AccountDetails(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountDetails as(Name alias) {
        return new AccountDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountDetails rename(String name) {
        return new AccountDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountDetails rename(Name name) {
        return new AccountDetails(name, null);
    }
}
