/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables;


import com.experts.core.biller.statemachine.api.jooq.Indexes;
import com.experts.core.biller.statemachine.api.jooq.Keys;
import com.experts.core.biller.statemachine.api.jooq.Public;
import com.experts.core.biller.statemachine.api.jooq.tables.records.BillerApiIntegrationsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BillerApiIntegrations extends TableImpl<BillerApiIntegrationsRecord> {

    private static final long serialVersionUID = -971648654;

    /**
     * The reference instance of <code>public.biller_api_integrations</code>
     */
    public static final BillerApiIntegrations BILLER_API_INTEGRATIONS = new BillerApiIntegrations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BillerApiIntegrationsRecord> getRecordType() {
        return BillerApiIntegrationsRecord.class;
    }

    /**
     * The column <code>public.biller_api_integrations.id</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.createddate</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, Timestamp> CREATEDDATE = createField("createddate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.biller_api_integrations.lastmodifiedby</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> LASTMODIFIEDBY = createField("lastmodifiedby", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.biller_api_integrations.modifieddate</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, Timestamp> MODIFIEDDATE = createField("modifieddate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.biller_api_integrations.username</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.biller_api_integrations.alias_name</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> ALIAS_NAME = createField("alias_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.billpull_url</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> BILLPULL_URL = createField("billpull_url", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.biller_name</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> BILLER_NAME = createField("biller_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.building_no</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> BUILDING_NO = createField("building_no", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.cert_content</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> CERT_CONTENT = createField("cert_content", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.email</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.file_name</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.floorno</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> FLOORNO = createField("floorno", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.biller_api_integrations.folder_name</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> FOLDER_NAME = createField("folder_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.payment_notification_url</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> PAYMENT_NOTIFICATION_URL = createField("payment_notification_url", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.phone_1</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> PHONE_1 = createField("phone_1", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.phone_2</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> PHONE_2 = createField("phone_2", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.biller_api_integrations.pk_content</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> PK_CONTENT = createField("pk_content", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.pox</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> POX = createField("pox", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.biller_api_integrations.pub_content</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> PUB_CONTENT = createField("pub_content", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.serial_number</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> SERIAL_NUMBER = createField("serial_number", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.street_address</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, String> STREET_ADDRESS = createField("street_address", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.protocol</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, Integer> PROTOCOL = createField("protocol", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.biller_api_integrations.version</code>.
     */
    public final TableField<BillerApiIntegrationsRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.biller_api_integrations</code> table reference
     */
    public BillerApiIntegrations() {
        this(DSL.name("biller_api_integrations"), null);
    }

    /**
     * Create an aliased <code>public.biller_api_integrations</code> table reference
     */
    public BillerApiIntegrations(String alias) {
        this(DSL.name(alias), BILLER_API_INTEGRATIONS);
    }

    /**
     * Create an aliased <code>public.biller_api_integrations</code> table reference
     */
    public BillerApiIntegrations(Name alias) {
        this(alias, BILLER_API_INTEGRATIONS);
    }

    private BillerApiIntegrations(Name alias, Table<BillerApiIntegrationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private BillerApiIntegrations(Name alias, Table<BillerApiIntegrationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BillerApiIntegrations(Table<O> child, ForeignKey<O, BillerApiIntegrationsRecord> key) {
        super(child, key, BILLER_API_INTEGRATIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BILLER_API_INTEGRATIONS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BillerApiIntegrationsRecord> getPrimaryKey() {
        return Keys.BILLER_API_INTEGRATIONS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BillerApiIntegrationsRecord>> getKeys() {
        return Arrays.<UniqueKey<BillerApiIntegrationsRecord>>asList(Keys.BILLER_API_INTEGRATIONS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillerApiIntegrations as(String alias) {
        return new BillerApiIntegrations(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillerApiIntegrations as(Name alias) {
        return new BillerApiIntegrations(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BillerApiIntegrations rename(String name) {
        return new BillerApiIntegrations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BillerApiIntegrations rename(Name name) {
        return new BillerApiIntegrations(name, null);
    }
}
