/*
 * This file is generated by jOOQ.
 */
package com.experts.core.biller.statemachine.api.jooq.tables;


import com.experts.core.biller.statemachine.api.jooq.Indexes;
import com.experts.core.biller.statemachine.api.jooq.Keys;
import com.experts.core.biller.statemachine.api.jooq.Public;
import com.experts.core.biller.statemachine.api.jooq.tables.records.SystemSettingsCatogreyRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemSettingsCatogrey extends TableImpl<SystemSettingsCatogreyRecord> {

    private static final long serialVersionUID = -458560847;

    /**
     * The reference instance of <code>public.system_settings_catogrey</code>
     */
    public static final SystemSettingsCatogrey SYSTEM_SETTINGS_CATOGREY = new SystemSettingsCatogrey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemSettingsCatogreyRecord> getRecordType() {
        return SystemSettingsCatogreyRecord.class;
    }

    /**
     * The column <code>public.system_settings_catogrey.id</code>.
     */
    public final TableField<SystemSettingsCatogreyRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.system_settings_catogrey.createddate</code>.
     */
    public final TableField<SystemSettingsCatogreyRecord, Timestamp> CREATEDDATE = createField("createddate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.system_settings_catogrey.lastmodifiedby</code>.
     */
    public final TableField<SystemSettingsCatogreyRecord, String> LASTMODIFIEDBY = createField("lastmodifiedby", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.system_settings_catogrey.modifieddate</code>.
     */
    public final TableField<SystemSettingsCatogreyRecord, Timestamp> MODIFIEDDATE = createField("modifieddate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.system_settings_catogrey.username</code>.
     */
    public final TableField<SystemSettingsCatogreyRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.system_settings_catogrey.name</code>.
     */
    public final TableField<SystemSettingsCatogreyRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.system_settings_catogrey.type</code>.
     */
    public final TableField<SystemSettingsCatogreyRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.system_settings_catogrey.version</code>.
     */
    public final TableField<SystemSettingsCatogreyRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.system_settings_catogrey</code> table reference
     */
    public SystemSettingsCatogrey() {
        this(DSL.name("system_settings_catogrey"), null);
    }

    /**
     * Create an aliased <code>public.system_settings_catogrey</code> table reference
     */
    public SystemSettingsCatogrey(String alias) {
        this(DSL.name(alias), SYSTEM_SETTINGS_CATOGREY);
    }

    /**
     * Create an aliased <code>public.system_settings_catogrey</code> table reference
     */
    public SystemSettingsCatogrey(Name alias) {
        this(alias, SYSTEM_SETTINGS_CATOGREY);
    }

    private SystemSettingsCatogrey(Name alias, Table<SystemSettingsCatogreyRecord> aliased) {
        this(alias, aliased, null);
    }

    private SystemSettingsCatogrey(Name alias, Table<SystemSettingsCatogreyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SystemSettingsCatogrey(Table<O> child, ForeignKey<O, SystemSettingsCatogreyRecord> key) {
        super(child, key, SYSTEM_SETTINGS_CATOGREY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYSTEM_SETTINGS_CATOGREY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SystemSettingsCatogreyRecord> getPrimaryKey() {
        return Keys.SYSTEM_SETTINGS_CATOGREY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SystemSettingsCatogreyRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemSettingsCatogreyRecord>>asList(Keys.SYSTEM_SETTINGS_CATOGREY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemSettingsCatogrey as(String alias) {
        return new SystemSettingsCatogrey(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemSettingsCatogrey as(Name alias) {
        return new SystemSettingsCatogrey(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemSettingsCatogrey rename(String name) {
        return new SystemSettingsCatogrey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemSettingsCatogrey rename(Name name) {
        return new SystemSettingsCatogrey(name, null);
    }
}
